import { AnimatePresence, motion } from 'framer-motion';
import { Sparkles } from 'lucide-react';
import { useState } from 'react';
import { ApiError, CATEGORIES, Category, ProjectIdeaResponse, api, toApiError } from '../lib/api';
import { Outline } from './Outline';
import { ErrorNote, cx } from './ui';

const LABELS: Record<Category, string> = { productivity: 'Productivity', education: 'Education', healthcare: 'Healthcare', finance: 'Finance', career: 'Career', other: 'Other' };

export function ProjectPicker({ userId }: { userId?: string }) {
  const [category, setCategory] = useState<Category | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<ApiError | null>(null);
  const [result, setResult] = useState<ProjectIdeaResponse | null>(null);

  const generate = async (c: Category) => {
    setCategory(c); setLoading(true); setError(null);
    try { setResult(await api.projectIdea(c, userId)); } catch (e) { setError(toApiError(e)); } finally { setLoading(false); }
  };

  return (
    <section aria-labelledby="ai-title" className="rounded-2xl border border-line bg-panel p-6 sm:p-8">
      <h2 id="ai-title" className="text-xl font-bold sm:text-2xl">What kind of AI project would you like to build?</h2>
      <p className="mt-1 text-sm text-muted">Pick an area and get a project idea with a 60-minute build plan.</p>
      <div role="radiogroup" aria-label="Project category" className="mt-5 flex flex-wrap gap-2">
        {CATEGORIES.map((c) => (
          <button key={c} role="radio" aria-checked={category === c} disabled={loading} onClick={() => generate(c)}
            className={cx('rounded-full border px-4 py-2 text-sm font-medium transition disabled:opacity-60', category === c ? 'border-saffron bg-saffron/15 text-saffron' : 'border-line hover:border-muted')}>
            {LABELS[c]}
          </button>
        ))}
      </div>

      <div aria-live="polite" className="mt-6">
        {loading && <p className="flex items-center gap-2 text-sm text-muted"><Sparkles className="h-4 w-4 animate-pulse text-saffron" aria-hidden /> Designing your project…</p>}
        {error && !loading && <ErrorNote message={error.message} onRetry={category ? () => generate(category) : undefined} />}
        <AnimatePresence mode="wait">
          {result && !loading && !error && (
            <motion.div key={result.idea.title} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} className="rounded-xl border border-line bg-ink/60 p-5 sm:p-6">
              <div className="flex flex-wrap items-center gap-2">
                <h3 className="text-lg font-bold sm:text-xl">{result.idea.title}</h3>
                <span className="rounded-full bg-aqua/15 px-2.5 py-0.5 text-xs font-semibold text-aqua">{result.idea.difficulty}</span>
              </div>
              <p className="mt-2 text-muted">{result.idea.oneLiner}</p>
              <ul className="mt-4 flex flex-wrap gap-2" aria-label="Suggested tech stack">
                {result.idea.techStack.map((t) => <li key={t} className="rounded-md border border-line px-2.5 py-1 font-mono text-xs">{t}</li>)}
              </ul>
              <h4 className="mb-3 mt-6 text-sm font-semibold">Your 60-minute plan</h4>
              <Outline steps={result.idea.outline} />
              <p className="mt-5 text-xs text-muted">
                {result.source === 'openai' ? 'Generated by AI for the category you picked.' : 'A curated suggestion for this category (AI generation is not enabled on this server).'}
              </p>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </section>
  );
}
